### ISSUE TITLE
Can't activate version press

### ISSUE THREAD

**Issue by aidanheerdegen** [versionpress/docs#62]
I'm getting file permissions problems, even though I have (as a test) made pretty much everything under html/ writeable by the apache user

Quick summary
array (
  'wordpress-version' => '4.5.2',
  'versionpress-version' => '3.0.1',
  'operating-system' => 'Linux ********************\* 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64',
  'php-version' => '5.6.22',
  'php-sapi' => 'apache2handler',
  'git-version' => '2.8.3',
  'git-full-path' => '/usr/bin/git
',
)
Git
array (
  'git-binary-as-configured' => 'git',
  'git-available' => true,
  'git-version' => '2.8.3',
  'git-binary-as-called-by-vp' => 'git',
  'git-full-path' => '/usr/bin/git
',
  'versionpress-min-required-version' => '1.9',
  'matches-min-required-version' => true,
)
Permissions
array (
  'exec-user' => 'apache',
  'proc_open-user' => 'apache',
  'php-can-write' => 
  array (
    'ABSPATH' => false,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'process-can-write' => 
  array (
    'ABSPATH' => false,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
  'php-can-delete-file-created-by-process' => 
  array (
    'ABSPATH' => true,
    'WP_CONTENT_DIR' => true,
    'sys_temp_dir' => true,
  ),
)

Where is ABSPATH defined?

I have restarted the https daemon.

**Comment by borekb** [comment]
Hi, this is a support issue, could you please re-submit the ticket [here](https://github.com/versionpress/support)? Thanks.
