### ISSUE TITLE
Document custom structure (#565)

### ISSUE THREAD

**Issue by JanVoracek** [versionpress/docs#9]
Document https://github.com/versionpress/versionpress/issues/565. There are only some supported scenarios of customising project structure. 
- [ ] Document supported scenarios
- [ ] Document public "VP_" constants, e.g., `VP_PROJECT_ROOT`, `VP_VPDB_DIR`.

**Comment by borekb** [comment]
We also ran a Google Form survey, we should compile the results as part of this task. See https://github.com/versionpress/versionpress/issues/565#issuecomment-172927267.

**Comment by borekb** [comment]
The survey results should be summarized into the issue, not docs. Removing it from the tasks.
